* Sales Management

In [1]:
# Setup 1 — Connect to database
import pandas as pd
from sqlalchemy import create_engine, text

DB_URL='postgresql+psycopg2://jayabharathi:GRGzARJJc8kpCYs3RdAeMrMZdOSTCiJ2@dpg-d7d4vvq8qa3s73b10540-a.singapore-postgres.render.com/salemanagementdb_flpa'
engine=create_engine(DB_URL)

# run_query — for SELECT DQL
def run_query(sql, params={}):
    with engine.connect() as conn:
        df = pd.read_sql(text(sql), conn, params=params)
    return df

#

# run_write — for INSERT, UPDATE, DELETE, DML
def run_write(sql, params={}):
    with engine.connect() as conn:
        result=conn.execute(text(sql), params)
        conn.commit()
    return result

In [1]:
# Setup 2 — Create tables and load data (run ONCE only)


from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text('DROP TABLE IF EXISTS branches,customer_sales,payment_splits,users CASCADE'))
    conn.execute(text('''
       CREATE TABLE branches (
         branch_id SERIAL  PRIMARY KEY,
         branch_name VARCHAR(100),
         branch_admin_name VARCHAR(100)
       )'''))
    conn.execute(text('''
       CREATE TABLE users (
         user_id SERIAL PRIMARY KEY,
         username VARCHAR(100),
         password VARCHAR(255),
         branch_id INT,
         role TEXT CHECK (role IN ('Super Admin', 'Admin')) ,
         email VARCHAR(255) UNIQUE,
         FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
       )'''))
    conn.execute(text('''
       CREATE TABLE customer_sales (
          sale_id SERIAL PRIMARY KEY,
          branch_id INT,
          date DATE,
          name VARCHAR(100),
          mobile_number VARCHAR(15),
          product_name VARCHAR(30),
          gross_sales DECIMAL(12,2),
          received_amount DECIMAL(12,2) DEFAULT 0,
          pending_amount DECIMAL(12,2)
    GENERATED ALWAYS AS (gross_sales - received_amount) STORED,

          status TEXT CHECK (status IN ('Open', 'Close')) DEFAULT 'Open',

           UNIQUE (mobile_number),
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
        )'''))
    conn.execute(text('''
      CREATE TABLE payment_splits (
          payment_id SERIAL PRIMARY KEY,
          sale_id INT,
          payment_date DATE,
          amount_paid DECIMAL(12,2),
          payment_method VARCHAR(50),

    FOREIGN KEY (sale_id) REFERENCES customer_sales(sale_id)
       )'''))
    conn.commit()
print("Tables created.")

for t in ['branches','customer_sales','payment_splits','users' ]:
    df = pd.read_csv(f'{t}.csv')
    df.to_sql(t, engine, if_exists='append', index=False)
    print(f"  {t}: {len(df):,} rows")

print("\nAll data loaded.")

NameError: name 'engine' is not defined

In [2]:
run_query('''
   select * from branches
''')

   branch_id branch_name branch_admin_name
0          1     Chennai        Arun Kumar
1          2   Bangalore      Ravi Shankar
2          3   Hyderabad      Suresh Reddy
3          4       Delhi       Neha Sharma
4          5      Mumbai       Rahul Mehta
5          6        Pune        Amit Patil
6          7     Kolkata      Subham Ghosh
7          8   Ahmedabad         Raj Patel

In [3]:
run_query('''
   SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer_sales';
''')

       column_name
0      gross_sales
1  received_amount
2   pending_amount
3          sale_id
4             date
5        branch_id
6           status
7             name
8    mobile_number
9     product_name

In [4]:
run_query('''
   select * from payment_splits
''')

      payment_id  sale_id payment_date  amount_paid payment_method
0              1        1   2024-01-06       7296.0           Cash
1              2        2   2024-01-04       7314.0           Card
2              3        3   2024-01-04       3457.0           Cash
3              4        3   2024-01-07        384.0           Cash
4              5        3   2024-01-12       1856.0           Card
...          ...      ...          ...          ...            ...
2009        2010     1000   2024-10-07       7596.0            UPI
2010        2011     1000   2024-09-28       1157.0           Card
2011        4022        1   2026-04-02      10000.0            UPI
2012        4023        1   2026-04-03       5000.0           Cash
2013        4024        2   2026-04-04      15000.0           Card

[2014 rows x 5 columns]

In [9]:

with engine.connect() as conn:
   conn.execute(text('''
CREATE OR REPLACE FUNCTION update_received_amount_funct()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE customer_sales
    SET received_amount = (
        SELECT COALESCE(SUM(amount_paid), 0)
        FROM payment_splits
        WHERE sale_id = NEW.sale_id
    )
    WHERE sale_id = NEW.sale_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
 '''))
   conn.commit()

In [6]:

with engine.connect() as conn:
   conn.execute(text('''
CREATE TRIGGER update_received_amount
AFTER INSERT ON payment_splits
FOR EACH ROW
EXECUTE FUNCTION update_received_amount_funct();
 '''))
   conn.commit()

ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "update_received_amount" for relation "payment_splits" already exists

[SQL:
CREATE TRIGGER update_received_amount
AFTER INSERT ON payment_splits
FOR EACH ROW
EXECUTE FUNCTION update_received_amount_funct();
 ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [2]:
run_query('''
 select * from customer_sales

''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open

In [3]:
run_query('''
 select * from payment_splits
 where sale_id=1
''')

   payment_id  sale_id payment_date  amount_paid payment_method
0           1        1   2024-01-06       7296.0           Cash
1        4022        1   2026-04-02      10000.0            UPI
2        4023        1   2026-04-03       5000.0           Cash

In [4]:

with engine.connect() as conn:
   conn.execute(text('''
   INSERT INTO payment_splits (payment_id, sale_id, payment_date, amount_paid, payment_method)
VALUES
(4022,1, '2026-04-02', 10000, 'UPI'),
(4023,1, '2026-04-03', 5000, 'Cash'),
(4024,2, '2026-04-04', 15000, 'Card');
'''))
   conn.commit()

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "payment_splits_pkey"
DETAIL:  Key (payment_id)=(4022) already exists.

[SQL:
   INSERT INTO payment_splits (payment_id, sale_id, payment_date, amount_paid, payment_method)
VALUES
(4022,1, '2026-04-02', 10000, 'UPI'),
(4023,1, '2026-04-03', 5000, 'Cash'),
(4024,2, '2026-04-04', 15000, 'Card');
]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [5]:
run_query ('''
select * from customer_sales
where status = 'Open'
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open

In [ ]:
#basic

In [6]:
run_query ('''
select * from customer_sales
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open

In [7]:
run_query ('''
select * from branches
''')

   branch_id branch_name branch_admin_name
0          1     Chennai        Arun Kumar
1          2   Bangalore      Ravi Shankar
2          3   Hyderabad      Suresh Reddy
3          4       Delhi       Neha Sharma
4          5      Mumbai       Rahul Mehta
5          6        Pune        Amit Patil
6          7     Kolkata      Subham Ghosh
7          8   Ahmedabad         Raj Patel

In [9]:
run_query ('''
select * from payment_splits
''')

      payment_id  sale_id payment_date  amount_paid payment_method
0              1        1   2024-01-06       7296.0           Cash
1              2        2   2024-01-04       7314.0           Card
2              3        3   2024-01-04       3457.0           Cash
3              4        3   2024-01-07        384.0           Cash
4              5        3   2024-01-12       1856.0           Card
...          ...      ...          ...          ...            ...
2009        2010     1000   2024-10-07       7596.0            UPI
2010        2011     1000   2024-09-28       1157.0           Card
2011        4022        1   2026-04-02      10000.0            UPI
2012        4023        1   2026-04-03       5000.0           Cash
2013        4024        2   2026-04-04      15000.0           Card

[2014 rows x 5 columns]

In [10]:
run_query ('''
select * from customer_sales WHERE status = 'Open'
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open

In [11]:
run_query ('''
select * from customer_sales WHERE branch_id = 1
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
1,8,1,2024-01-09,Customer_8,9800000008,BA,30000.0,0.0,30000.0,Open
2,11,1,2024-01-12,Customer_11,9800000011,DA,35000.0,0.0,35000.0,Open
3,23,1,2024-01-24,Customer_23,9800000023,BA,30000.0,0.0,30000.0,Open
4,35,1,2024-02-05,Customer_35,9800000035,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
105,962,1,2024-08-20,Customer_962,9800000962,FSD,45000.0,0.0,45000.0,Open
106,973,1,2024-08-31,Customer_973,9800000973,DS,40000.0,0.0,40000.0,Open
107,980,1,2024-09-07,Customer_980,9800000980,SQL,25000.0,0.0,25000.0,Open
108,981,1,2024-09-08,Customer_981,9800000981,BA,30000.0,0.0,30000.0,Open
109,988,1,2024-09-15,Customer_988,9800000988,DA,35000.0,0.0,35000.0,Open

In [10]:
run_query ('''
SELECT SUM(gross_sales) FROM customer_sales;
''')

          sum
0  36768000.0

In [12]:
run_query ('''
SELECT SUM(pending_amount) FROM customer_sales;
''')

          sum
0  36723390.0

In [13]:
run_query ('''
SELECT branch_id, COUNT(*)
FROM customer_sales GROUP BY branch_id;
''')

   branch_id  count
0          8    128
1          7    133
2          1    110
3          5    136
4          2    133
5          4    134
6          6    120
7          3    106

In [17]:
run_query ('''
SELECT AVG(gross_sales) FROM customer_sales;
''')

       avg
0  36768.0

In [ ]:
# joins

In [18]:
run_query ('''
SELECT cs.*, b.branch_name
FROM customer_sales cs
JOIN branches b ON cs.branch_id = b.branch_id;
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status,branch_name
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open,Delhi
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open,Bangalore
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open,Kolkata
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open,Chennai
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open,Delhi
...,...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open,Pune
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open,Kolkata
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open,Mumbai
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open,Bangalore
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open,Mumbai

In [20]:
run_query ('''

SELECT cs.sale_id, ps.payment_method
FROM customer_sales cs
JOIN payment_splits ps ON cs.sale_id = ps.sale_id;

''')

      sale_id payment_method
0           1           Cash
1           2           Card
2           3           Cash
3           3           Cash
4           3           Card
...       ...            ...
2009     1000            UPI
2010     1000           Card
2011        1            UPI
2012        1           Cash
2013        2           Card

[2014 rows x 2 columns]

In [21]:
run_query ('''

SELECT cs.*, b.branch_admin_name
FROM customer_sales cs
JOIN branches b ON cs.branch_id = b.branch_id;

''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status,branch_admin_name
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open,Neha Sharma
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open,Ravi Shankar
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open,Subham Ghosh
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open,Arun Kumar
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open,Neha Sharma
...,...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open,Amit Patil
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open,Subham Ghosh
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open,Rahul Mehta
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open,Ravi Shankar
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open,Rahul Mehta

In [ ]:
#🔹 Financial Insights

In [22]:
run_query ('''
SELECT * FROM customer_sales WHERE pending_amount > 5000;
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,3,4,2024-01-04,Customer_3,9800000003,DA,35000.0,0.0,35000.0,Open
1,4,2,2024-01-05,Customer_4,9800000004,FSD,45000.0,0.0,45000.0,Open
2,5,7,2024-01-06,Customer_5,9800000005,DS,40000.0,0.0,40000.0,Open
3,6,1,2024-01-07,Customer_6,9800000006,FSD,45000.0,0.0,45000.0,Open
4,7,4,2024-01-08,Customer_7,9800000007,BA,30000.0,0.0,30000.0,Open
...,...,...,...,...,...,...,...,...,...,...
995,998,6,2024-09-25,Customer_998,9800000998,SQL,25000.0,0.0,25000.0,Open
996,999,7,2024-09-26,Customer_999,9800000999,DA,35000.0,0.0,35000.0,Open
997,1000,5,2024-09-27,Customer_1000,9800001000,SQL,25000.0,0.0,25000.0,Open
998,1,2,2024-01-02,Customer_1,9800000001,DS,40000.0,22296.0,17704.0,Open
999,2,5,2024-01-03,Customer_2,9800000002,BA,30000.0,22314.0,7686.0,Open

In [23]:
run_query ('''
SELECT * FROM customer_sales ORDER BY gross_sales DESC LIMIT 3;
''')

,sale_id,branch_id,date,name,mobile_number,product_name,gross_sales,received_amount,pending_amount,status
0,12,7,2024-01-13,Customer_12,9800000012,AI,48000.0,0.0,48000.0,Open
1,14,4,2024-01-15,Customer_14,9800000014,AI,48000.0,0.0,48000.0,Open
2,17,6,2024-01-18,Customer_17,9800000017,AI,48000.0,0.0,48000.0,Open

In [24]:
run_query ('''
SELECT branch_id, SUM(gross_sales) AS total
FROM customer_sales
GROUP BY branch_id
ORDER BY total DESC LIMIT 1;
''')

   branch_id      total
0          7  5101000.0

In [13]:
run_query ('''
SELECT
  EXTRACT(MONTH FROM date) AS month,
  EXTRACT(YEAR FROM date) AS year,
    SUM(gross_sales)
FROM customer_sales
GROUP BY year, month;
''')

    month    year        sum
0     8.0  2024.0  3254000.0
1     2.0  2024.0  3116000.0
2     1.0  2024.0  3487000.0
3     5.0  2024.0  3418000.0
4     4.0  2024.0  3272000.0
5    10.0  2024.0  2362000.0
6    12.0  2024.0  2175000.0
7     3.0  2024.0  3442000.0
8    11.0  2024.0  2248000.0
9     7.0  2024.0  3517000.0
10    6.0  2024.0  3294000.0
11    9.0  2024.0  3183000.0

In [26]:
run_query ('''

SELECT payment_method, SUM(amount_paid)
FROM payment_splits
GROUP BY payment_method;

''')

  payment_method        sum
0            UPI  6043099.0
1           Card  6623008.0
2           Cash  6392006.0

In [ ]:
run_query ('''

''')

In [ ]:
run_query ('''

''')